language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  # "2.7"
  # "pypy"

install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements_tests.txt

script:
  - pep8 picopayments_cli
  - py.test --ignore=env --verbose --cov-config=.coveragerc --cov-report=term-missing --cov=./picopayments_cli -vv

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
