language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements_tests.txt

script:
  - pep8 picopayments_cli
  - py.test --ignore=env --verbose --cov-config=.coveragerc --cov-report=term-missing --cov=./picopayments_cli -vv

after_success:
  - coveralls

notifications:
  slack: 
    secure: cl0G5fWZNnIK5VQ6BPZ4RtwVO2/nfvX/zjhljfF6cQ20OKyvyiJHq+e67fl2pkCKDlqlEqSWaQJ6G52YzUpDQmf+o7qpH6YnkFxSqYp5h4YF1hJw4sCHJ7bVSLrjogWxU8QaNvH7YpL4YkGe+WOau2FgoIZOcMt6hhKrvWclfuc=
